version: '2'
services:
  studycentermicroservice-mongodb:
    image: mongo:4.2.7
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/studycentermicroservice/mongodb/:/data/db/
